#!/bin/bash

set -e

setupDir() {
    if [ ! -e $1 ]; then
        mkdir $1
    fi
}

setupDirs() {
    setupDir build
    setupDir bin
}


main () {
    setupDirs
    if [ $1 == j ] || [ $1 == java ]; then
        javac -cp src/java:testing -d build testing/Test.java
        java -cp build testing.Test
    elif [ $1 == p ] || [ $1 == python ]; then
        PYTHONPATH=$PYTHONPATH:src/python
        python testing/test.py
    elif [ $1 == g ] || [ $1 == go ] || [ $1 == golang ]; then
        GOPATH=$GOPATH:$(pwd) go build testing/test.go
        mv test bin/gotest
        GOPATH=$GOPATH:$(pwd) go run testing/test.go
    elif [ $1 == clean ]; then
        rm -rf build
        rm -rf bin
        find . -name "*.hi" | xargs rm
        find . -name "*.o" | xargs rm
    fi
}

main $@
